### ISSUE TITLE
Feed the history

### ISSUE THREAD

**Issue by Callidus2000** [mdgrs-mei/RestartableSession#4] opened 2023-02-23 13:30 UTC
Commands used in an RSS most (not every time) are not recorded in the command history. Therefor they are not recommended by PSReadline.

Any Idea how to fix this? After the automatic restart it would be nice to recall the last test command from the history 😏 

For reproduction:
```Powershell
Enter-RSSession
Write-Host "Foo"
Restart-RSSession
```
From the history I can get `Enter-RSSession` and `Restart-RSSession` but no command between.

**Comment by mdgrs-mei** [comment] 2023-02-23 14:10
I'm using PSReadLine 2.2.6 and it recommends the `Write-Host "Foo"` command even after `Restart-RSSession` in your reproduction case. 

- What version do you use? 
- Right after the `Write-Host` before calling `Restart-RSSession`, does PSReadLine suggest it?

**Comment by Callidus2000** [comment] 2023-02-24 06:59
Good morning...
Lesson learned yesterday: Never open issues on "All Goes Wrong" days...
Same PSReadLine version. My problem occurs while I'm developing my SecretManagement extension, therefor my `OnStart` block and the whole use case is much bigger than to put into this ticket... My fault was to just simplify the issue in mind and do net test the example...

You're right, my example is working... I'll try to figure out under which circumstances the problem occurs and come back to this afterwards...

**Comment by mdgrs-mei** [comment] 2023-02-24 13:22
No problem, I'm happy to help!

If the last command in your example is `Exit-RSSession`, `Write-Host` is not suggested because PSReadLine does not reflect the history of another session untill a new session is started. I think it's the design.

```powershell
# session A
Enter-RSSession
# session B
Write-Host "Foo"
Exit-RSSession
# session A
W... # not suggested
```

**Comment by mdgrs-mei** [comment] 2024-03-30 09:10
@Callidus2000 I'm going to close this issue once as I was not be able to reproduce it. Please reopen this if you see that again. Thanks!

**Closed by mdgrs-mei** 2024-03-30 09:10 UTC
